name: 'Build and Push with Nix and Docker'
description: 'Check Nix flakes, build Nix packages and Docker containers, and push the containers'
inputs:
  packages:
    description: 'List of Nix packages to build, comma separated values'
    required: false
    default: ''
  containers:
    description: 'List of Docker containers to build and push, comma separated values'
    required: false
    default: ''
  publish:
   description: 'List of packages to publish, comma separated values'
   required: false
   default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v3

    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v4

    - name: Nix Flake Check
      run: nix flake check
      shell: bash

    - name: Build Packages
      run: |
        if [ -z "${{ inputs.packages }}" ]; then
          nix build
        else
          for package in ${{ inputs.packages }}; do
            nix build .#$package --out-link result-$package
          done
        fi
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-packages
        path: ./result
